[programs.localnet]
nft_trade = "6yMsjNTLtgkC1rUaJCjPeESt34Cd4nDSyVqn2i4qm1oy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet =  "/home/jeronimo/config/solana/devnet-test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
